name: releasing

on:
  push:
    branches:
      - main
      - beta

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          echo "yarn_dir_path=$(yarn cache dir)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ${{ env.yarn_dir_path }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Set git user
        run: |
          git config --global user.email "<>"
          git config --global user.name "openameba"
      - run: yarn build
      # Create tag with release note
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
